# Generated by Django 3.2.7 on 2021-09-30 00:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.CharField(default='Not Specified', max_length=200, verbose_name='creator name'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='row_version',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='total iterations'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='updated_by',
            field=models.CharField(default='system', max_length=200, verbose_name='updated by name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 0, 36, 57, 493882, tzinfo=utc), verbose_name='date to be published'),
        ),
    ]
