# Generated by Django 3.2.7 on 2021-09-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210929_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='total_votes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date to be published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_by',
            field=models.CharField(default='Not Specified', max_length=200, verbose_name='updated by name'),
        ),
    ]
